import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/page";
import Providers from "@/Components/theme/theme-provider";
import Footer from "@/Components/Footer/page";
import ArrowUp from "@/Components/ArrowUp/ArrowUp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Souls Type",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <Header />
          {children}
          <ArrowUp />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
